spring:
  config:
    import: classpath:application.yaml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/code_masters
    username: root
    password: C0mpl3xpb@369
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
